In [5]:
# Created Employee class with name, family, salary and department
class Employee:

    # declared a data member to count the number of Employees
    no_of_employees = 0

    # constructor to initialize the object's attributes
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

    # declared average_salary function to return average salary
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees

# Created a Fulltime Employee class and inherited the properties of Employee class
class FulltimeEmployee(Employee):
    """
    Full Time Employee is a sub class of Employee
    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_member(self):
        print("Calling FulltimeEmployee member function.")

# Created the instances of Fulltime Employee class and Employee class and calling their member functions.
def main():
    employees = []
    ftEmployee1 = FulltimeEmployee("Vamshi", "Ponugoti", 140000, "Software Engineering")
    ftEmployee1.full_time_member()
    employees.append(ftEmployee1)
    ftEmployee2 = FulltimeEmployee("Micheal", "Velayudham", 170000, "Cyber Security")
    employees.append(ftEmployee2)
    employee1 = Employee("CoseC", "Pacchipulsula", 150000, "Testing")
    employees.append(employee1)
    employee2 = Employee("VeeraSimhaReddy", "Nandamuri", 192000, "Product Manager")
    employees.append(employee2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))

# declared this method to execute code When the file runs as a script.
if __name__ == "__main__":
    main()

Calling FulltimeEmployee member function.
Average salary: 163000.0


In [7]:
import numpy as np
# created a random vector of size 20 with float values between 1 and 20
ranvec = np.random.uniform(low=1, high=20, size=20)
print(ranvec)
# reshape the array to 4 by 5 using reshape method
mat45 = ranvec.reshape(4, 5)
print(mat45)
# replace the max in each row by 0 using where method
mat45 = np.where(mat45 == np.amax(mat45, axis=1, keepdims=True), 0, mat45)
print(mat45)


[11.52893107 15.55864345 15.34299709 19.01923719  4.03866576  7.24033005
  6.88551941 11.52420218 16.05710437 19.23360177  1.857521    8.60712665
  4.04348398 12.17366495 12.01280991  8.48274022 14.58174168  5.24870941
 19.5857353   9.90350164]
[[11.52893107 15.55864345 15.34299709 19.01923719  4.03866576]
 [ 7.24033005  6.88551941 11.52420218 16.05710437 19.23360177]
 [ 1.857521    8.60712665  4.04348398 12.17366495 12.01280991]
 [ 8.48274022 14.58174168  5.24870941 19.5857353   9.90350164]]
[[11.52893107 15.55864345 15.34299709  0.          4.03866576]
 [ 7.24033005  6.88551941 11.52420218 16.05710437  0.        ]
 [ 1.857521    8.60712665  4.04348398  0.         12.01280991]
 [ 8.48274022 14.58174168  5.24870941  0.          9.90350164]]
